name: Build and Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Authenticate with Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

    # Step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT }}

    # Step 4: Copy files to VM instance
    - name: Copy files to VM instance
      run: |
        gcloud compute scp --recurse ./ ${{ secrets.GCLOUD_VM_NAME }}:/path/on/vm --zone ${{ secrets.GCLOUD_ZONE }}

    # Step 5: Connect to VM and start/restart the app
    - name: SSH into VM and deploy
      run: |
        gcloud compute ssh ${{ secrets.GCLOUD_VM_NAME }} --zone ${{ secrets.GCLOUD_ZONE }} --command "
        cd /path/on/vm &&
        npm install &&
        pm2 restart app || pm2 start your-app-file.js --name app
        "
